(function(){
'use strict';
const days=['Domenica','Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato'];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Europe/Rome'});
const stamp=x=>new Date(x).toLocaleString('it-IT',{timeZone:'Europe/Rome',weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});
const clock=n=>String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');
const minutes=x=>{const a=x.split(':').map(Number);return a[0]*60+a[1];};
function style(){if(document.getElementById('visit-slot-style'))return;const s=document.createElement('style');s.id='visit-slot-style';s.textContent='.visit-settings{margin-bottom:18px}.visit-settings summary{cursor:pointer;font-weight:800;padding:12px 0}.visit-fields{display:flex;gap:12px;flex-wrap:wrap}.visit-fields label{display:grid;gap:5px;min-width:140px;flex:1}.visit-fields input,.visit-fields select,.visit-settings textarea{width:100%;padding:10px;border:1px solid #cedce4;border-radius:10px;box-sizing:border-box}.visit-window{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:10px 0}.visit-window select,.visit-window input{padding:8px;border:1px solid #cedce4;border-radius:9px;min-width:90px}.visit-window button{margin-left:auto}.visit-slots-grid{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.visit-slots-grid button{min-height:44px;border:1px solid #a4c8b5;border-radius:10px;padding:9px 12px;background:#f3faf6;color:#245642}.visit-slots-grid button[aria-pressed=true]{background:#245642;color:white}.visit-result{margin-top:10px;line-height:1.5}.visit-preview{padding:12px;border:1px solid #c5ded0;border-radius:12px;background:#f3faf6;margin:12px 0}.visit-settings .btn,.visit-booking .btn{min-height:44px}';document.head.append(s);}
async function doctorPanel({root,sb,getUserId}){
 if(!root||root.dataset.visitOwner===getUserId())return;style();const owner=getUserId();root.dataset.visitOwner=owner;root.innerHTML='<p>Caricamento disponibilità…</p>';
 const {data,error}=await sb.from('clinician_visit_settings').select('*').eq('clinician_id',owner).maybeSingle();
 if(!root.isConnected||owner!==getUserId())return;
 if(error){root.dataset.visitOwner='';root.textContent='Disponibilità non caricate: '+error.message;return;}
 const cfg=data||{enabled:false,duration_minutes:30,notice_hours:2,horizon_days:30,weekly_windows:[],blocked_dates:[],location_type:'in_person',location_label:''};
 root.innerHTML=`<details class="visit-settings" ${cfg.enabled?'open':''}><summary>Disponibilità prenotabili dai pazienti</summary><p>Facoltative. Gli orari sono italiani. Le prenotazioni sono confermate automaticamente; le visite già in agenda occupano l’orario.</p><label><input class="visit-enabled" type="checkbox" ${cfg.enabled?'checked':''}> Attiva le prenotazioni dall’app</label><div class="visit-fields" style="margin:14px 0"><label>Durata visita (minuti)<input class="visit-duration" type="number" min="5" max="180" value="${cfg.duration_minutes}"></label><label>Preavviso minimo (ore)<input class="visit-notice" type="number" min="0" max="168" value="${cfg.notice_hours}"></label><label>Giorni prenotabili in anticipo<input class="visit-horizon" type="number" min="7" max="90" value="${cfg.horizon_days}"></label></div><div class="visit-fields"><label>Tipo di visita<select class="visit-mode"><option value="in_person">In presenza</option><option value="phone">Telefonica</option><option value="video">Video</option></select></label><label>Luogo / indicazioni<input class="visit-location" maxlength="300" value="${esc(cfg.location_label)}"></label></div><h4>Fasce settimanali</h4><div class="visit-windows"></div><button type="button" class="btn secondary visit-add">Aggiungi fascia</button><label style="display:grid;gap:6px;margin:16px 0">Date da bloccare (AAAA-MM-GG, una per riga)<textarea class="visit-blocks" rows="3" placeholder="2026-12-25">${esc(cfg.blocked_dates.join('\n'))}</textarea></label><button type="button" class="btn visit-save">Salva disponibilità</button><p>Disattivare l’agenda o bloccare una data impedisce nuove prenotazioni; gli appuntamenti confermati restano in agenda.</p><div class="visit-result" role="status" aria-live="polite"></div></details>`;
 root.querySelector('.visit-mode').value=cfg.location_type;
 const holder=root.querySelector('.visit-windows');function add(w={day:1,start:540,end:780}){const row=document.createElement('div');row.className='visit-window';row.innerHTML=`<select aria-label="Giorno">${days.map((d,i)=>`<option value="${i}">${d}</option>`).join('')}</select><input type="time" aria-label="Dalle" value="${clock(w.start)}"><span>alle</span><input type="time" aria-label="Alle" value="${clock(w.end===1440?0:w.end)}"><button type="button" class="btn secondary">Rimuovi</button>`;row.querySelector('select').value=w.day;row.querySelector('button').onclick=()=>row.remove();holder.append(row);}
 cfg.weekly_windows.forEach(add);root.querySelector('.visit-add').onclick=()=>add();
 root.querySelector('.visit-save').onclick=async()=>{const button=root.querySelector('.visit-save'),result=root.querySelector('.visit-result');button.disabled=true;result.textContent='Salvataggio…';
  try{const weekly=[...holder.children].map(row=>{const inputs=row.querySelectorAll('input');if(!inputs[0].value||!inputs[1].value)throw Error('Completa gli orari delle fasce');return {day:Number(row.querySelector('select').value),start:minutes(inputs[0].value),end:minutes(inputs[1].value)||1440};});const blocked=root.querySelector('.visit-blocks').value.split(/[\s,;]+/).filter(Boolean);if(blocked.some(x=>!/^\d{4}-\d{2}-\d{2}$/.test(x)))throw Error('Usa il formato AAAA-MM-GG per le date bloccate');
   if(owner!==getUserId())return;const {error}=await sb.rpc('save_visit_settings',{p_settings:{enabled:root.querySelector('.visit-enabled').checked,duration_minutes:Number(root.querySelector('.visit-duration').value),notice_hours:Number(root.querySelector('.visit-notice').value),horizon_days:Number(root.querySelector('.visit-horizon').value),location_type:root.querySelector('.visit-mode').value,location_label:root.querySelector('.visit-location').value.trim(),weekly_windows:weekly,blocked_dates:[...new Set(blocked)]}});if(error)throw error;if(root.isConnected&&owner===getUserId())result.textContent='Disponibilità salvate. I pazienti collegati vedranno gli orari liberi.';
  }catch(e){if(root.isConnected&&owner===getUserId())result.textContent=e.message||'Salvataggio non riuscito';}finally{if(root.isConnected&&owner===getUserId())button.disabled=false;}
 };
}
function patientPanel({root,sb,getContext,onBooked}){
 if(!root)return;style();const initial=getContext();const key=JSON.stringify(initial);const valid=()=>root.isConnected&&key===JSON.stringify(getContext());let disposed=false,sequence=0,selected=null,booking=false;
 const live=()=>!disposed&&valid();root.classList.add('visit-booking');
 if(!initial?.clinicianId){root.innerHTML='<h2>Prenota una visita</h2><p>Seleziona prima il tuo medico.</p>';return;}
 root.innerHTML='<h2>Prenota una visita</h2><p>Disponibilità del medico selezionato, aggiornate automaticamente. Orari italiani.</p><label>Da quale giorno? <input class="visit-from" type="date"></label> <button type="button" class="btn secondary visit-refresh">Aggiorna orari</button><div class="visit-options"></div><div class="visit-selection"></div><div class="visit-result" role="status" aria-live="polite"></div>';
 const input=root.querySelector('.visit-from');input.value=today();input.min=today();const options=root.querySelector('.visit-options'),preview=root.querySelector('.visit-selection'),result=root.querySelector('.visit-result');
 function draw(data){options.innerHTML='';if(!data.enabled){options.textContent='Il medico non ha attivato la prenotazione online. Puoi contattarlo con “Scrivi al medico”.';selected=null;preview.innerHTML='';return;}
  if(!data.slots.length){options.textContent='Nessun orario libero nei prossimi 7 giorni a partire dalla data scelta. Prova un’altra data o scrivi al medico.';}
  for(const slot of data.slots){const btn=document.createElement('button');btn.type='button';btn.textContent=stamp(slot.start);btn.setAttribute('aria-pressed',String(selected?.start===slot.start));btn.onclick=()=>{if(!live()||booking)return;selected=slot;renderSelection(data);draw(data);};if(!options.firstChild){const list=document.createElement('div');list.className='visit-slots-grid';options.append(list);}options.firstChild.append(btn);}
  if(selected&&!data.slots.some(s=>s.start===selected.start)){selected=null;preview.innerHTML='';result.textContent='L’orario selezionato non è più libero: scegline un altro.';}
 }
 function renderSelection(data){preview.innerHTML=`<div class="visit-preview"><strong>${esc(stamp(selected.start))} · ${data.duration_minutes} minuti</strong><p>${esc(({in_person:'In presenza',phone:'Telefonica',video:'Video'})[data.location_type])}${data.location_label?' · '+esc(data.location_label):''}</p><label>Motivo della visita (facoltativo)<input class="visit-reason" maxlength="500"></label><button type="button" class="btn visit-confirm">Conferma prenotazione</button></div>`;
  preview.querySelector('.visit-confirm').onclick=async()=>{if(!live()||booking||!selected)return;booking=true;sequence++;const chosen=selected;const btn=preview.querySelector('.visit-confirm');btn.disabled=true;result.textContent='Conferma della prenotazione…';try{const {data:booked,error}=await sb.rpc('book_visit_slot',{p_clinician:initial.clinicianId,p_start:chosen.start,p_reason:preview.querySelector('.visit-reason').value.trim()||null});if(error)throw error;if(!live())return;selected=null;preview.innerHTML='';result.textContent='Visita confermata: '+stamp(chosen.start);await refresh();if(live())await onBooked?.(booked);}catch(e){if(live()){selected=null;preview.innerHTML='';result.textContent=e.message||'Prenotazione non riuscita';await refresh();}}finally{booking=false;if(live()&&btn.isConnected)btn.disabled=false;}};
 }
 async function refresh(){if(!live()||booking&&selected)return;const current=++sequence;try{const {data,error}=await sb.rpc('get_free_visit_slots',{p_clinician:initial.clinicianId,p_from:input.value||today(),p_days:7});if(!live()||current!==sequence)return;if(error)throw error;draw(data);}catch(e){if(live()&&current===sequence)options.textContent='Orari non caricati: '+(e.message||'Riprova.');}}
 input.onchange=()=>{selected=null;preview.innerHTML='';refresh();};root.querySelector('.visit-refresh').onclick=refresh;
 const channel=sb.channel?.('visit-availability:'+initial.clinicianId+':'+Math.random().toString(36).slice(2)).on('postgres_changes',{event:'*',schema:'public',table:'visit_availability_updates',filter:'clinician_id=eq.'+initial.clinicianId},refresh).subscribe();const cleanup=()=>{if(channel)sb.removeChannel(channel);};
 const timer=setInterval(refresh,15000);const observer=new MutationObserver(()=>{if(!valid()){disposed=true;clearInterval(timer);observer.disconnect();cleanup();}});observer.observe(document.body,{childList:true,subtree:true});refresh();return ()=>{disposed=true;clearInterval(timer);observer.disconnect();cleanup();};
}
window.MeditalyVisits={doctorPanel,patientPanel};
})();
