begin;
create temporary table visit_qa as select gen_random_uuid() doctor,gen_random_uuid() patient,gen_random_uuid() patient2,gen_random_uuid() outsider,((now() at time zone 'Europe/Rome')::date+1) visit_day;
grant select on visit_qa to authenticated;
insert into auth.users(id,raw_user_meta_data) select doctor,'{}'::jsonb from visit_qa union all select patient,'{}'::jsonb from visit_qa union all select patient2,'{}'::jsonb from visit_qa union all select outsider,'{}'::jsonb from visit_qa;
update public.profiles set account_active=true where id in(select doctor from visit_qa union all select patient from visit_qa union all select patient2 from visit_qa union all select outsider from visit_qa);
update public.profiles set role='Clinician' where id=(select doctor from visit_qa);
insert into public.patient_clinicians(patient_id,clinician_id,active) select patient,doctor,true from visit_qa union all select patient2,doctor,true from visit_qa;
create temporary table visit_state(id uuid,start timestamptz);grant all on visit_state to authenticated;
select set_config('request.jwt.claims',json_build_object('sub',(select patient from visit_qa),'role','authenticated')::text,true);set local role authenticated;
do $$begin if (public.get_free_visit_slots((select doctor from visit_qa),(select visit_day from visit_qa),1)->>'enabled')::boolean then raise exception 'Default opt-in was enabled';end if;end $$;
reset role;
select set_config('request.jwt.claims',json_build_object('sub',(select doctor from visit_qa),'role','authenticated')::text,true);set local role authenticated;
select public.save_visit_settings(jsonb_build_object('enabled',true,'duration_minutes',30,'notice_hours',0,'horizon_days',30,'weekly_windows',(select jsonb_agg(jsonb_build_object('day',d,'start',540,'end',600)) from generate_series(0,6) d),'blocked_dates',jsonb_build_array(((select visit_day from visit_qa)+1)::text)));
do $$begin begin perform public.save_visit_settings('{"enabled":true,"duration_minutes":30,"weekly_windows":[{"day":1,"start":540,"end":600},{"day":1,"start":570,"end":660}]}'::jsonb);raise exception 'Overlap allowed';exception when others then if sqlerrm not like '%sovrappongono%' then raise;end if;end;end $$;
reset role;
select set_config('request.jwt.claims',json_build_object('sub',(select patient from visit_qa),'role','authenticated')::text,true);set local role authenticated;
do $$declare slots jsonb; booked jsonb; t timestamptz;begin
 if exists(select 1 from public.clinician_visit_settings where clinician_id=(select doctor from visit_qa)) then raise exception 'Patient read private schedule settings';end if;
 slots:=public.get_free_visit_slots((select doctor from visit_qa),(select visit_day from visit_qa),1);
 if jsonb_array_length(slots->'slots')<>2 then raise exception 'Wrong slot count: %',slots;end if;
 t:=(slots#>>'{slots,0,start}')::timestamptz;
 booked:=public.book_visit_slot((select doctor from visit_qa),t,'Synthetic test');insert into visit_state values((booked->>'appointment_id')::uuid,t);
 if not exists(select 1 from public.appointments where id=(booked->>'appointment_id')::uuid and status='Confirmed' and booked_slot and duration_minutes=30) then raise exception 'Booking not confirmed';end if;
 if jsonb_array_length(public.get_free_visit_slots((select doctor from visit_qa),(select visit_day from visit_qa),1)->'slots')<>1 then raise exception 'Booked slot still available';end if;
 if jsonb_array_length(public.get_free_visit_slots((select doctor from visit_qa),(select visit_day+1 from visit_qa),1)->'slots')<>0 then raise exception 'Blocked date available';end if;
end $$;
reset role;
select set_config('request.jwt.claims',json_build_object('sub',(select patient2 from visit_qa),'role','authenticated')::text,true);set local role authenticated;
do $$begin
 begin perform public.book_visit_slot((select doctor from visit_qa),(select start from visit_state),null);raise exception 'Double booking allowed';exception when others then if sqlerrm not like 'Questo orario non è più disponibile%' then raise;end if;end;
 if exists(select 1 from public.appointments where id=(select id from visit_state)) then raise exception 'Other patient appointment exposed';end if;
 begin perform public.change_visit_booking((select id from visit_state),'cancel');raise exception 'Other patient cancelled booking';exception when others then if sqlerrm<>'Prenotazione non accessibile' then raise;end if;end;
end $$;
reset role;
select set_config('request.jwt.claims',json_build_object('sub',(select doctor from visit_qa),'role','authenticated')::text,true);set local role authenticated;
do $$begin begin perform public.propose_appointment((select patient2 from visit_qa),(select start from visit_state),30,null,'in_person',null,null);raise exception 'Manual overlap allowed';exception when others then if sqlerrm<>'Il medico ha già un appuntamento in questo orario' then raise;end if;end;end $$;
reset role;
select set_config('request.jwt.claims',json_build_object('sub',(select outsider from visit_qa),'role','authenticated')::text,true);set local role authenticated;
do $$begin begin perform public.get_free_visit_slots((select doctor from visit_qa),(select visit_day from visit_qa),1);raise exception 'Unlinked slot access';exception when others then if sqlerrm<>'Medico non collegato al tuo account' then raise;end if;end;end $$;
reset role;
select set_config('request.jwt.claims',json_build_object('sub',(select patient from visit_qa),'role','authenticated')::text,true);set local role authenticated;
do $$begin
 begin perform public.save_visit_settings('{}'::jsonb);raise exception 'Patient changed settings';exception when others then if sqlerrm<>'Solo il medico può configurare la propria agenda' then raise;end if;end;
 perform public.change_visit_booking((select id from visit_state),'cancel');
 if jsonb_array_length(public.get_free_visit_slots((select doctor from visit_qa),(select visit_day from visit_qa),1)->'slots')<>2 then raise exception 'Cancelled slot not freed';end if;
end $$;
reset role;
rollback;
select 'PASS: opt-in, slots, booking, collision, manual overlap, cancellation, blocked dates, link and RLS checks' as result;
